version: '3'
services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DATABASE}?schema=public
    command:
      sh -c "npm install && npx prisma generate && npx prisma migrate deploy && npm start"
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  postgres_data:

